pipeline {
    agent {
        docker {
            image 'docker.internal.kevinlin.info/infra/ci-base:0.3.5'
            label 'docker-executor'
        }
    }

    options {
        withAWS(
            endpointUrl: 'https://storage.kevinlin.info',
            credentials: 'storage-internal',
        )
    }

    stages {
        stage('Install') {
            steps {
                sh 'npm-s3 install'
            }
        }
        stage('Test') {
            parallel {
                stage('Build') {
                    steps {
                        sh 'npm run build'
                    }
                }
                stage('Lint') {
                    steps {
                        sh 'npm run lint'
                    }
                }
                stage('Unit') {
                    steps {
                        sh 'npm run cover'
                    }
                }
            }
        }
        stage('Build') {
            steps {
                sh 'npm run prepublish'
                sh 'cd lib/ && npm pack'
            }
        }
        stage('Release') {
            steps {
                sh 'mv -v lib/*.tgz release.tgz'
                sh 'tar -cvzf release.tar.gz release.tgz'
                s3Upload(
                    bucket: 'internal',
                    path: "deploy/${env.JOB_NAME}/${env.GIT_COMMIT}/",
                    file: 'release.tar.gz',
                )
            }
        }
        stage('Deploy') {
            steps {
                build(
                    job: 'task--js-library',
                    parameters: [
                        string(name: 'RELEASE_ARTIFACT', value: env.JOB_NAME),
                        string(name: 'RELEASE_VERSION', value: env.GIT_COMMIT),
                        string(name: 'PACKAGE_NAME', value: env.JOB_NAME),
                        string(name: 'PACKAGE_VERSION', value: env.GIT_COMMIT),
                    ],
                    wait: true,
                )
            }
        }
    }
}
